/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;
import service.XMLBuilder;
import service.XMLReader;

/**
 *
 * @author M
 */
public class StoresJDialog extends javax.swing.JDialog {

    java.util.HashMap<String, Boolean> stores;
    /**
     * Creates new form StoresJDialog
     */
    public StoresJDialog(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
	this.setLocationRelativeTo(parent);
	
	this.stores = new java.util.HashMap<>();
	try {
	    loadSettings();
	    updateStoresSettings();
	} catch (ParserConfigurationException | IOException | SAXException ex) {
	    JOptionPane.showMessageDialog(null, "Can't load settings.", "Error", 
		    JOptionPane.ERROR_MESSAGE, null);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        mainTPane = new javax.swing.JTabbedPane();
        storesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ozonCHBox = new javax.swing.JCheckBox();
        advCHBox = new javax.swing.JCheckBox();
        ozonLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Настройки");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(75, 25));
        okButton.setMinimumSize(new java.awt.Dimension(75, 25));
        okButton.setPreferredSize(new java.awt.Dimension(75, 25));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Отметьте онлайн-магазины для поиска:");

        ozonCHBox.setName("Ozon"); // NOI18N

        advCHBox.setText("Здесь может быть ваш магазин!");
        advCHBox.setEnabled(false);

        ozonLabel.setText("<html><a href=\\\"http://www.ozon.ru\\\">Ozon</a></html>");

        javax.swing.GroupLayout storesPanelLayout = new javax.swing.GroupLayout(storesPanel);
        storesPanel.setLayout(storesPanelLayout);
        storesPanelLayout.setHorizontalGroup(
            storesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(storesPanelLayout.createSequentialGroup()
                        .addComponent(ozonCHBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ozonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(advCHBox))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        storesPanelLayout.setVerticalGroup(
            storesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(storesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ozonCHBox)
                    .addComponent(ozonLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advCHBox)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        mainTPane.addTab("Stores", storesPanel);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(75, 25));
        cancelButton.setMinimumSize(new java.awt.Dimension(75, 25));
        cancelButton.setPreferredSize(new java.awt.Dimension(75, 25));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainTPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
	try (PrintWriter writer = new PrintWriter("src\\settings.xml")) {
	    String xml = XMLBuilder.createProperties(stores);
	    writer.print(xml);
	} catch (ParserConfigurationException | TransformerException | FileNotFoundException ex) {
	    JOptionPane.showMessageDialog(null, "Error while saving settings. Settings are not saved.",
		    "Error", JOptionPane.ERROR_MESSAGE, null);
	}
	updateStoresMap();
	
	this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox advCHBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane mainTPane;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox ozonCHBox;
    private javax.swing.JLabel ozonLabel;
    private javax.swing.JPanel storesPanel;
    // End of variables declaration//GEN-END:variables

    private void loadSettings() throws ParserConfigurationException, IOException, SAXException {
	this.stores.putAll(XMLReader.loadSettings("src\\settings.xml"));
    }

    private void updateStoresMap() {
	Component[] components = this.storesPanel.getComponents();
	for (Component comp : components) {
	    if (comp instanceof JCheckBox) {
		String name = ((JCheckBox) comp).getName();
		if (name != null) {
		    Boolean isSelected = ((JCheckBox) comp).isSelected();
		    stores.put(name, isSelected);
		}
	    }
	}
    }

    private void updateStoresSettings() {
	Component[] components = this.storesPanel.getComponents();
	for (Component comp : components) {
	    if (comp instanceof JCheckBox) {
		String name = ((JCheckBox) comp).getName();
		Boolean isSelected = this.stores.get(name);
		if (isSelected != null) {
		    ((JCheckBox) comp).setSelected(isSelected);
		}
	    }
	}
    }
}
